name: Build and publish Builder (linux/amd64)

on:
  push:
    tags:
      - 'builder/*'

jobs:  
  build_publish:
    uses: ./.github/workflows/build.yml
    with:
      platform: linux/amd64
    secrets: inherit